#include <Arduino.h>

/*
   -- bluetooth --

   To compile this code using RemoteXY library 4.1.8 or later version
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;

   To interact with the GUI, please refer to the manual:
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and
   is an example for the RemoteXY library.
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license
   details.
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG

// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings
#define REMOTEXY_BLUETOOTH_NAME "RemoteXY"

/* the first measured value of the first point */
#define SENS_1_VAL 514
#define SENS_1_TMP 36.6

/* the second measured value of the second point */
#define SENS_2_VAL 580
#define SENS_2_TMP 25.0

#include <RemoteXY.h>

// RemoteXY GUI configuration
#pragma pack(push, 1)
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 31 bytes V19
  { 255,11,0,0,0,24,0,19,0,0,0,0,31,1,106,200,1,1,1,0,
  7,26,58,60,15,102,64,2,26,2,11 };

// this structure defines all the variables and events of your control interface
struct {

    // input variables
  char sensor_01[11]; // string UTF8 end zero

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;
#pragma pack(pop)

/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////




void setup()
{
  RemoteXY_Init ();  // initialization by macros


  // TODO you setup code

}

void loop()
{
  RemoteXYEngine.handler ();


  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXYEngine.delay()
  //
  /* get the ADC value */
  // int sensorValue = analogRead(A5);
   int sensorValue = random(0, 1024);
   /*
     calculated current temperature using
     a linear interpolation on the two known points
   */
   double temp = SENS_1_TMP + (SENS_2_TMP - SENS_1_TMP) /
             (SENS_2_VAL - SENS_1_VAL) * (sensorValue - SENS_1_VAL);
   /*
     convert the temperature value into a string
     and place it immediately in the field text_1 patterns RemoteXY
   */
   dtostrf(temp, 0, 1, RemoteXY.sensor_01);

   /*
     send the value of the ADC to Serial
     in order that we could check the values
   */
   Serial.println(sensorValue);
   RemoteXYEngine.delay(10);

}
